### ISSUE TITLE
Reduce number of outgoing connections

### ISSUE THREAD

**Issue by ferchault** [NablaChem/hummingqueue#34]
Current setup costs 3 connections per worker. With 1.5k workers, this is too much for our local network policy.

Envoy does not support transactions or pub/sub as required by rq. Twemproxy is deprecated and does not support upstream TLS (required here by having an unsecured connection to the queue) but might work otherwise rq/rq#1976.

Steps needed: 
- [x] Move redis instance into the data center.
- [x] Remove HTTP and redis proxying.
- [x] Move maintenance logic to director.
- [x] Cache function payload in redis.
- [x] Upload results from new permanent agent using a finite number of HTTP connections.

Security model:
- Network within the data center is trusted, clients within the data center are not, so AUTH but no TLS.
- Director/uploading agent is trusted, since we cannot reasonably protect against it being compromised.

Tested envoy configuration:
```
static_resources:
  listeners:
  - name: api_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 42425
    filter_chains:
    - filters:
       - name: envoy.filters.network.tcp_proxy
         typed_config:
           "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
           stat_prefix: api
           cluster: api
  - name: redis_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 42424
    filter_chains:
    - filters:
      - name: envoy.filters.network.redis_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy
          stat_prefix: egress_redis
          settings:
            op_timeout: 10s
          downstream_auth_password:
            inline_string: "..."
          prefix_routes:
            catch_all_route:
              cluster: redis
  clusters:
  - name: api
    connect_timeout: 30s
    type: STRICT_DNS
    dns_refresh_rate: "500s"
    dns_lookup_family: V4_ONLY
    http2_protocol_options: {}
    load_assignment:
      cluster_name: api
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: hmq.nablachem.org
                    port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: "hmq.nablachem.org"
  - name: redis
    type: STRICT_DNS
    dns_refresh_rate: "500s"
    dns_lookup_family: "V4_ONLY"
    load_assignment:
      cluster_name: redis
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: redis.nablachem.org
                port_value: 443
    typed_extension_protocol_options:
      envoy.filters.network.redis_proxy:
        "@type": type.googleapis.com/google.protobuf.Struct
        value:
          auth_password:
            inline_string: "..."
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: "redis.nablachem.org"
admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```
